#!/bin/sh

alias ls="ls --color=auto --group-directories-first"
alias l="ls -lah"

alias grep="grep --color=auto"
alias egrep="grep -E"
alias fgrep="grep -F"

alias cd..="cd .."

alias gs="git status"
alias ga="git add"
alias ga.="git add ."
alias gaa="git add ."
alias gap="git add -p"
alias gd="git diff"
alias gds="git diff --staged"
alias gc="git commit"
alias gcm="git commit --message"
alias gl="git log"
alias gls="git log --stat"
alias gll="git log --graph --abbrev-commit --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset'"
alias glp="git log --patch"
alias gla="git log --stat --patch"
alias gfa="git fetch --all"
alias gp="git push"
alias grom="git rebase origin/master --autostash"
alias gromi="git rebase origin/master -i --autostash"
